export interface MediaCard {
  id: number;
  title: string;
  originalTitle?: string;
  year: number;
  rating: number;
  poster: string;
  backdrop?: string;
  quality: string;
  type: "movie" | "series" | "anime";
  tags?: string[];
  duration?: string;
  genres?: string[];
  story?: string;
  isSeries?: boolean;
  seasonCount?: number;
  episodeCount?: number;
  status?: string;
}

export interface HomeSection {
  id: string;
  title: string;
  slug: string;
  items: MediaCard[];
}

export interface HeroSlide {
  id: number;
  title: string;
  originalTitle: string;
  story: string;
  backdrop: string;
  poster: string;
  year: number;
  rating: number;
  quality: string;
  genres: string[];
  tags: string[];
  type: "movie" | "series";
  duration: string;
  mediaId: number;
}

const posters = ["/poster1.jpg", "/poster2.jpg", "/poster3.jpg", "/poster4.jpg"];

function makeCard(id: number, overrides: Partial<MediaCard> = {}): MediaCard {
  const types: Array<MediaCard["type"]> = ["movie", "series", "anime"];
  return {
    id,
    title: "",
    originalTitle: "",
    year: 2024,
    rating: 7.0,
    poster: posters[id % 4],
    quality: "1080p",
    type: types[id % 3],
    tags: [],
    ...overrides,
  };
}

export const heroSlides: HeroSlide[] = [
  {
    id: 1,
    title: "مرد الخلد والوولفرين",
    originalTitle: "Deadpool & Wolverine",
    story:
      "في عالم متعدد الأبعاد، يتم استدعاء ويد ويلسون من قبل هيئة الزمن المتغيرة لمهمة إنقاذ الكون المتعدد. يواجه تهديداً وجودياً مع وولفرين في مغامرة مليئة بالأكشن والكوميديا الساخرة.",
    backdrop: "/backdrop.jpg",
    poster: "/poster1.jpg",
    year: 2024,
    rating: 7.8,
    quality: "1080p WEB-DL",
    genres: ["أكشن", "مغامرة", "كوميدي"],
    tags: ["جديد", "HD", "حصري"],
    type: "movie",
    duration: "2س 7د",
    mediaId: 1,
  },
  {
    id: 2,
    title: "صراع العروش",
    originalTitle: "Game of Thrones",
    story:
      "في عالم خيالي حيث الصيف يدوم لسنوات والشتاء قد يستمر عمراً كاملاً، تقع سبع عائلات نبيلة في صراع مرير على السيطرة على عرش ويستروس. تتشابك مصائر شخصيات متعددة في شبكة معقدة من السياسة والخيانة.",
    backdrop: "/backdrop.jpg",
    poster: "/poster4.jpg",
    year: 2011,
    rating: 9.2,
    quality: "1080p BluRay",
    genres: ["دراما", "مغامرة", "فانتازيا"],
    tags: ["HD"],
    type: "series",
    duration: "8 مواسم",
    mediaId: 2,
  },
  {
    id: 3,
    title: "هجوم العمالقة: النهاية",
    originalTitle: "Attack on Titan: The Final Season",
    story:
      "بعد سنوات من القتال ضد العمالقة، يصل إيرين يايغر إلى الحقيقة المروعة وراء أصل العمالقة والقوة التحويلية. يتحدى أصدقاؤه السابقون كل ما آمنوا به في معركة نهائية ستحدد مصير البشرية.",
    backdrop: "/backdrop.jpg",
    poster: "/poster3.jpg",
    year: 2024,
    rating: 9.0,
    quality: "1080p WEB-DL",
    genres: ["أنمي", "أكشن", "دراما"],
    tags: ["جديد", "HD", "حصري"],
    type: "series",
    duration: "الموسم الأخير",
    mediaId: 3,
  },
  {
    id: 4,
    title: "خانق الأسود: طريق الماء",
    originalTitle: "Black Panther: Wakanda Forever",
    story:
      "بعد وفاة الملك تشالا، تواجه مملكة واكندا تهديداً عالمياً جديداً. يجب على الملكة راموندا وشوريهي:black بانثر:ر:ا الحماية واكندا من القوى العالمية التي تسعى للسيطرة على موارد الـفيبرانيوم.",
    backdrop: "/backdrop.jpg",
    poster: "/poster2.jpg",
    year: 2024,
    rating: 7.1,
    quality: "1080p WEB-DL",
    genres: ["أكشن", "مغامرة", "خيال علمي"],
    tags: ["HD"],
    type: "movie",
    duration: "2س 41د",
    mediaId: 4,
  },
];

export const homeSections: HomeSection[] = [
  {
    id: "trending",
    title: "الأكثر رواجاً",
    slug: "trending",
    items: [
      makeCard(1, {
        title: "مرد الخلد والوولفرين",
        originalTitle: "Deadpool & Wolverine",
        rating: 7.8,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["جديد", "HD"],
        type: "movie",
      }),
      makeCard(2, {
        title: "خانق الأسود 2",
        originalTitle: "Black Panther 2",
        rating: 7.1,
        poster: "/poster2.jpg",
        quality: "1080p",
        tags: ["HD"],
        type: "movie",
      }),
      makeCard(3, {
        title: "نهاية اللعبة",
        originalTitle: "Endgame",
        rating: 8.4,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(4, {
        title: "غانج 4",
        originalTitle: "Gangs of London S4",
        rating: 8.2,
        poster: "/poster4.jpg",
        quality: "1080p",
        tags: ["مسلسل مستمر"],
        type: "series",
        isSeries: true,
        seasonCount: 4,
      }),
      makeCard(5, {
        title: "هجوم العمالقة",
        originalTitle: "Attack on Titan",
        rating: 9.0,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["حصري"],
        type: "anime",
      }),
      makeCard(6, {
        title: "أوبنهايمر",
        originalTitle: "Oppenheimer",
        rating: 8.9,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(7, {
        title: "بيت التنين",
        originalTitle: "House of the Dragon",
        rating: 8.5,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 2,
      }),
      makeCard(8, {
        title: "جون ويك 4",
        originalTitle: "John Wick 4",
        rating: 7.6,
        poster: "/poster4.jpg",
        quality: "1080p",
        tags: ["HD"],
        type: "movie",
      }),
      makeCard(9, {
        title: "ون بيس",
        originalTitle: "One Piece",
        rating: 8.7,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "anime",
      }),
      makeCard(10, {
        title: "الصقر الأسود",
        originalTitle: "The Black Phone",
        rating: 7.2,
        poster: "/poster2.jpg",
        quality: "720p",
        type: "movie",
      }),
    ],
  },
  {
    id: "new-releases",
    title: "المضاف حديثاً",
    slug: "new-releases",
    items: [
      makeCard(11, {
        title: "غواصة",
        originalTitle: "Submarine",
        year: 2025,
        rating: 7.4,
        poster: "/poster3.jpg",
        quality: "1080p",
        tags: ["جديد", "HD", "حصري"],
        type: "movie",
      }),
      makeCard(12, {
        title: "الموسم الثاني: الحارس الليلي",
        originalTitle: "Night Agent S2",
        year: 2025,
        rating: 7.8,
        poster: "/poster4.jpg",
        quality: "1080p",
        tags: ["جديد", "مسلسل مستمر"],
        type: "series",
        isSeries: true,
        seasonCount: 2,
      }),
      makeCard(13, {
        title: "المورق: بداية جديدة",
        originalTitle: "Dune: Part Two",
        year: 2024,
        rating: 8.6,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["جديد", "HD"],
        type: "movie",
      }),
      makeCard(14, {
        title: "سولو ليفلينغ",
        originalTitle: "Solo Leveling",
        year: 2024,
        rating: 8.4,
        poster: "/poster2.jpg",
        quality: "1080p",
        tags: ["جديد", "حصري"],
        type: "anime",
      }),
      makeCard(15, {
        title: "الفارس الظلام",
        originalTitle: "The Dark Knight",
        year: 2024,
        rating: 9.0,
        poster: "/poster3.jpg",
        quality: "4K",
        tags: ["جديد", "HD"],
        type: "movie",
      }),
      makeCard(16, {
        title: "عهد الكلاب",
        originalTitle: "Reign of Dogs",
        year: 2025,
        rating: 6.9,
        poster: "/poster4.jpg",
        quality: "1080p",
        tags: ["جديد"],
        type: "movie",
      }),
      makeCard(17, {
        title: "ظل المحارب",
        originalTitle: "Shadow Warrior",
        year: 2024,
        rating: 7.3,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["جديد"],
        type: "anime",
      }),
      makeCard(18, {
        title: "وادي الذئاب",
        originalTitle: "Valley of Wolves",
        year: 2025,
        rating: 7.0,
        poster: "/poster2.jpg",
        quality: "720p",
        tags: ["جديد"],
        type: "series",
        isSeries: true,
        seasonCount: 1,
      }),
    ],
  },
  {
    id: "foreign-movies",
    title: "أفلام أجنبية",
    slug: "foreign-movies",
    items: [
      makeCard(20, {
        title: "إنترستيلار",
        originalTitle: "Interstellar",
        year: 2014,
        rating: 8.7,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(21, {
        title: "مصاصة الحلوى",
        originalTitle: "Django Unchained",
        year: 2012,
        rating: 8.5,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(22, {
        title: "يوم الجمعة",
        originalTitle: "Friday",
        year: 2023,
        rating: 7.0,
        poster: "/poster3.jpg",
        quality: "720p",
        type: "movie",
      }),
      makeCard(23, {
        title: "السرداب",
        originalTitle: "The Cellar",
        year: 2022,
        rating: 5.8,
        poster: "/poster4.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(24, {
        title: "بداية",
        originalTitle: "Inception",
        year: 2010,
        rating: 8.8,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(25, {
        title: "القاتل",
        originalTitle: "The Killer",
        year: 2023,
        rating: 7.2,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(26, {
        title: "الفارس المظلم",
        originalTitle: "The Dark Knight",
        year: 2008,
        rating: 9.0,
        poster: "/poster3.jpg",
        quality: "4K",
        type: "movie",
      }),
      makeCard(27, {
        title: "باركاسيون",
        originalTitle: "Parasite",
        year: 2019,
        rating: 8.5,
        poster: "/poster4.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(28, {
        title: "حرب النجوم",
        originalTitle: "Star Wars",
        year: 2023,
        rating: 7.9,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(29, {
        title: "الماتريكس",
        originalTitle: "The Matrix",
        year: 1999,
        rating: 8.7,
        poster: "/poster2.jpg",
        quality: "4K",
        type: "movie",
      }),
    ],
  },
  {
    id: "foreign-series",
    title: "مسلسلات أجنبية",
    slug: "foreign-series",
    items: [
      makeCard(30, {
        title: "بيت الورق",
        originalTitle: "Money Heist",
        year: 2017,
        rating: 8.2,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 5,
      }),
      makeCard(31, {
        title: "لاعب الشطرنج",
        originalTitle: "The Queen's Gambit",
        year: 2020,
        rating: 8.6,
        poster: "/poster4.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(32, {
        title: "مثير: كوري",
        originalTitle: "Squid Game",
        year: 2021,
        rating: 8.0,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["حصري"],
        type: "series",
        isSeries: true,
        seasonCount: 2,
      }),
      makeCard(33, {
        title: "بريكينج باد",
        originalTitle: "Breaking Bad",
        year: 2008,
        rating: 9.5,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 5,
      }),
      makeCard(34, {
        title: "ماندالوريان",
        originalTitle: "The Mandalorian",
        year: 2019,
        rating: 8.3,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 3,
      }),
      makeCard(35, {
        title: "أخوة ساموراي",
        originalTitle: "Shogun",
        year: 2024,
        rating: 8.7,
        poster: "/poster4.jpg",
        quality: "1080p",
        tags: ["جديد", "حصري"],
        type: "series",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(36, {
        title: "الوريث",
        originalTitle: "Succession",
        year: 2018,
        rating: 8.9,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 4,
      }),
      makeCard(37, {
        title: "لا ستاردست",
        originalTitle: "Stranger Things",
        year: 2016,
        rating: 8.7,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 4,
      }),
      makeCard(38, {
        title: "ثور: وحش مورمون",
        originalTitle: "Under the Bridge",
        year: 2024,
        rating: 7.5,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(39, {
        title: "فايلز",
        originalTitle: "Fargo",
        year: 2014,
        rating: 8.9,
        poster: "/poster4.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 5,
      }),
    ],
  },
  {
    id: "anime",
    title: "أنمي",
    slug: "anime",
    items: [
      makeCard(40, {
        title: "ون بيس",
        originalTitle: "One Piece",
        year: 1999,
        rating: 8.7,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["مستمر"],
        type: "anime",
        isSeries: true,
        episodeCount: 1100,
      }),
      makeCard(41, {
        title: "ناروتو شيبودن",
        originalTitle: "Naruto Shippuden",
        year: 2007,
        rating: 8.3,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "anime",
        isSeries: true,
        episodeCount: 500,
      }),
      makeCard(42, {
        title: "دراغون بول سوبر",
        originalTitle: "Dragon Ball Super",
        year: 2015,
        rating: 7.6,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "anime",
        isSeries: true,
        episodeCount: 131,
      }),
      makeCard(43, {
        title: "جوجوتسو كايسن",
        originalTitle: "Jujutsu Kaisen",
        year: 2020,
        rating: 8.6,
        poster: "/poster4.jpg",
        quality: "1080p",
        tags: ["جديد"],
        type: "anime",
        isSeries: true,
        seasonCount: 2,
      }),
      makeCard(44, {
        title: "سولو ليفلينغ",
        originalTitle: "Solo Leveling",
        year: 2024,
        rating: 8.4,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["جديد", "حصري"],
        type: "anime",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(45, {
        title: "ديمون سلاير",
        originalTitle: "Demon Slayer",
        year: 2019,
        rating: 8.9,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "anime",
        isSeries: true,
        seasonCount: 4,
      }),
      makeCard(46, {
        title: "سباي إكس فاميلي",
        originalTitle: "Spy x Family",
        year: 2022,
        rating: 8.4,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "anime",
        isSeries: true,
        seasonCount: 2,
      }),
      makeCard(47, {
        title: "تانكو الملكة",
        originalTitle: "Queen's Blade",
        year: 2023,
        rating: 7.1,
        poster: "/poster4.jpg",
        quality: "720p",
        type: "anime",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(48, {
        title: "شوجن أراين",
        originalTitle: "Shogun Arise",
        year: 2024,
        rating: 7.8,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["جديد"],
        type: "anime",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(49, {
        title: "بلاد الخلود",
        originalTitle: "Frieren",
        year: 2023,
        rating: 9.1,
        poster: "/poster2.jpg",
        quality: "1080p",
        tags: ["حصري"],
        type: "anime",
        isSeries: true,
        seasonCount: 1,
      }),
    ],
  },
  {
    id: "asian-movies",
    title: "أفلام آسيوية",
    slug: "asian-movies",
    items: [
      makeCard(50, {
        title: "باراسايت",
        originalTitle: "Parasite",
        year: 2019,
        rating: 8.5,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(51, {
        title: "أولدبوي",
        originalTitle: "Oldboy",
        year: 2003,
        rating: 8.4,
        poster: "/poster4.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(52, {
        title: "العاصفة: ملاذ",
        originalTitle: "The Wailing",
        year: 2016,
        rating: 7.5,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(53, {
        title: "تدريب: بيانو",
        originalTitle: "Train to Busan",
        year: 2016,
        rating: 7.6,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(54, {
        title: "هاتف المحمول",
        originalTitle: "Burning",
        year: 2018,
        rating: 7.9,
        poster: "/poster3.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(55, {
        title: "حكاية الكاتبة",
        originalTitle: "Poetry",
        year: 2010,
        rating: 7.8,
        poster: "/poster4.jpg",
        quality: "720p",
        type: "movie",
      }),
      makeCard(56, {
        title: "النينجا الأخير",
        originalTitle: "Rurouni Kenshin",
        year: 2023,
        rating: 7.3,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(57, {
        title: "قصر الشمس",
        originalTitle: "Infernal Affairs",
        year: 2002,
        rating: 8.0,
        poster: "/poster2.jpg",
        quality: "1080p",
        type: "movie",
      }),
    ],
  },
  {
    id: "arabic-content",
    title: "أفلام ومسلسلات عربية",
    slug: "arabic-content",
    items: [
      makeCard(60, {
        title: "الكاهن",
        originalTitle: "The Priest",
        year: 2024,
        rating: 7.2,
        poster: "/poster3.jpg",
        quality: "1080p",
        tags: ["جديد"],
        type: "movie",
      }),
      makeCard(61, {
        title: "ولي العهد",
        originalTitle: "The Crown Prince",
        year: 2024,
        rating: 8.1,
        poster: "/poster4.jpg",
        quality: "1080p",
        tags: ["مسلسل مستمر"],
        type: "series",
        isSeries: true,
        seasonCount: 2,
      }),
      makeCard(62, {
        title: "بيت السلاطين",
        originalTitle: "Sultans' House",
        year: 2024,
        rating: 7.5,
        poster: "/poster1.jpg",
        quality: "1080p",
        type: "series",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(63, {
        title: "الفارس الأسود",
        originalTitle: "Black Knight",
        year: 2023,
        rating: 6.8,
        poster: "/poster2.jpg",
        quality: "720p",
        type: "movie",
      }),
      makeCard(64, {
        title: "حكايات زمن",
        originalTitle: "Time Tales",
        year: 2024,
        rating: 7.0,
        poster: "/poster3.jpg",
        quality: "1080p",
        tags: ["جديد", "حصري"],
        type: "series",
        isSeries: true,
        seasonCount: 1,
      }),
      makeCard(65, {
        title: "طريق النور",
        originalTitle: "Path of Light",
        year: 2023,
        rating: 7.4,
        poster: "/poster4.jpg",
        quality: "1080p",
        type: "movie",
      }),
      makeCard(66, {
        title: "مملكة النار",
        originalTitle: "Kingdom of Fire",
        year: 2024,
        rating: 7.9,
        poster: "/poster1.jpg",
        quality: "1080p",
        tags: ["جديد"],
        type: "series",
        isSeries: true,
        seasonCount: 3,
      }),
      makeCard(67, {
        title: "آخر الرجال",
        originalTitle: "Last of Men",
        year: 2023,
        rating: 6.5,
        poster: "/poster2.jpg",
        quality: "720p",
        type: "movie",
      }),
    ],
  },
];

// Search results mock
export const allMediaItems: MediaCard[] = homeSections.flatMap(
  (section) => section.items
);
