// ============================================================
// CinemaPlus - TMDB Seed Script
// بيانات 42 فيلم حقيقي مع بوستر من Letterboxd
// ============================================================
// الاستخدام:
//   npx tsx prisma/seed-tmdb.ts
// ============================================================

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const movies = [
  { id: "tmdb-157336", title: "إنترستيلار", originalTitle: "Interstellar", slug: "interstellar-2014", overview: "فيلم إنترستيلار هي قصة مستوحاة من رحلة كريستوفر نولان الخاصة عبر الزمن والمكان، تدور أحداث الفيلم في المستقبل حيث يواجه البشر خطر الانقراض بسبب أزمة غذائية حادة. يقرر كوبر، وهو مهندس زراعي وأب لابنتين، الانضمام إلى فريق من الرواد بقيادة البروفيسور براند في مهمة فضائية عبر ثقب دودي بالقرب من زحل للبحث عن كوكب جديد صالح للحياة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/1/1/7/6/2/1/117621-interstellar-0-500-0-750-crop.jpg", backdropUrl: "https://a.ltrbxd.com/resized/sm/upload/r4/0u/oq/0i/interstellar-1200-1200-675-675-crop-000000.jpg", releaseYear: 2014, quality: "1080p", rating: 8.7, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-475557", title: "جوكر", originalTitle: "Joker", slug: "joker-2019", overview: "آرثر فليك، رجل يعيش وحيداً في المجتمع ويعاني من اضطراب نفسي. يحاول أن يجد مكاناً لنفسه في مدينة غوثام المظلمة، لكنه يواجه الرفض والسخرية من الجميع. يحاول آرثر أن يكون ممثلاً كوميدياً لكنه يفشل، مما يؤدي إلى تحوله التدريجي إلى الشخصية الشريرة الشهيرة جوكر.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/4/0/6/7/7/5/406775-joker-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2019, quality: "1080p", rating: 8.4, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-27205", title: "البداءة", originalTitle: "Inception", slug: "inception-2010", overview: "دوم كوب هو لص محترف يختص في سرقة الأسرار من أعماق العقل الباطن أثناء النوم. يعقد صفقة مع رجل أعمال قوي للقيام بمهمة معاكسة تماماً وهي زراعة فكرة في عقل شخص آخر. يجب على كوب أن يجمع فريقاً من المتخصصين لتنفيذ هذه المهمة المستحيلة التي تتطلب الغوص في عدة طبقات من الأحلام.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/5/1/8/51518-the-matrix-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2010, quality: "1080p", rating: 8.8, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-278", title: "الخلاص من شاوشانك", originalTitle: "The Shawshank Redemption", slug: "shawshank-redemption-1994", overview: "يُحكم على المصرفي أندي دوفرين بالسجن المؤبد بتهمة قتل زوجته وعشيقها رغم براءته. داخل سجن شاوشانك، يتعرف أندي على السجين ريد الذي يصبح صديقه المقرب. على مدى عشرين عاماً، يحاول أندي التكيف مع حياة السجن بينما يخطط سراً لهروبه.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/5/6/8/51568-fight-club-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1994, quality: "1080p", rating: 9.3, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-238", title: "الأب الروحي", originalTitle: "The Godfather", slug: "godfather-1972", overview: "أحداث الفيلم تدور حول عائلة كورليون المافيوية في نيويورك خلال الأربعينيات والخمسينيات من القرن الماضي. يبدأ فيتو كورليون كزعيم لعائلة المافيا الأقوى، ويتولى ابنه مايكل قيادة العائلة بعد اغتيال الأخير. يروي الفيلم قصة الصعود والسقوط والخيانة داخل عالم المافيا.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/8/4/6/51846-dead-poets-society-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1972, quality: "1080p", rating: 9.2, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-680", title: "خيال رخيص", originalTitle: "Pulp Fiction", slug: "pulp-fiction-1994", overview: "يتكون الفيلم من ثلاث قصص متشابكة تدور في عالم الجريمة في لوس أنجلوس. القصة الأولى عن قاتلين مأجورين يعملان لصالح عصابة، والثانية عن ملاكم يرفض خسارة مباراة، والثالثة عن زوجين من اللصوص. تتفاعل هذه الشخصيات بطرق غير متوقعة في هذا الفيلم الأسطوري لكوينتن تارانتينو.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/4/4/4/51444-pulp-fiction-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1994, quality: "1080p", rating: 8.9, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-550", title: "نادي القتال", originalTitle: "Fight Club", slug: "fight-club-1999", overview: "رجل أعمال مجهول الاسم يعاني من الأرق الشديد ويمر بأزمة وجودية. يلتقي بTyler Durden وهو رجل غامض وجذاب، ويتفقان على تأسيس نادٍ سري للقتال بالأيادي العارية في قبو بار. يتحول النادي تدريجياً إلى حركة أناركية تهدد النظام الرأسمالي بأكمله.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/5/6/8/51568-fight-club-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1999, quality: "1080p", rating: 8.8, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-155", title: "فارس الظلام", originalTitle: "The Dark Knight", slug: "dark-knight-2008", overview: "باتمان يواجه أخطر خصومه على الإطلاق: الجوكر، مجرم عبقري ومجنون يثير الفوضى في مدينة غوثام. يضع الجوكر باتمان في مواقف مستحيلة ويجبره على اتخاذ قرارات أخلاقية صعبة. مع تعاون الملازم جوردون والمدعي العام هارفي دينت، يحاول باتمان إنقاذ المدينة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/3/4/5/51345-se7en-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2008, quality: "1080p", rating: 9.0, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-496243", title: "طفيلي", originalTitle: "Parasite / 기생충", slug: "parasite-2019", overview: "عائلة كيم الفقيرة تعيش في شقة صغيرة تحت الأرض. عندما يعرض الابن الأكبر كي وو خدماته كمدرس خاص لابنة عائلة بارك الغنية، يبدأ التسلل التدريجي لجميع أفراد عائلة كيم إلى حياة عائلة بارك. لكن الأسرار المظلمة تكشف نفسها ببطء مما يؤدي إلى نهاية مأساوية.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/4/2/6/4/0/6/426406-parasite-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2019, quality: "1080p", rating: 8.5, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-13", title: "فورست غامب", originalTitle: "Forrest Gump", slug: "forrest-gump-1994", overview: "فورست غامب رجل بسيط من ألاباما يمتلك قلباً طيباً رغم معدل ذكائه المنخفض. يعيش فورست مغامرات استثنائية خلال عقود عديدة، حيث يشارك في حرب فيتنام ويصبح بطلاً رياضياً ورجل أعمال ناجحاً. طوال حياته، يحب فورست جيني التي يعرفها منذ الطفولة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/2/7/0/4/2704-forrest-gump-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1994, quality: "1080p", rating: 8.8, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-346698", title: "باربي", originalTitle: "Barbie", slug: "barbie-2023", overview: "باربي تعيش في باربي لاند وهي عالم مثالي مليء بالنساء الجميلات. لكن يوماً ما تلاحظ تغيرات غريبة في جسدها وعالمها. عليها أن تسافر إلى العالم الحقيقي لإيجاد حل، فتذهب مع كين إلى لوس أنجلوس في مغامرة مضحكة مليئة بالدروس عن الهوية والذات.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/2/7/7/0/6/4/277064-barbie-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2023, quality: "1080p", rating: 7.0, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-872585", title: "أوبنهايمر", originalTitle: "Oppenheimer", slug: "oppenheimer-2023", overview: "الفيلم يروي قصة العالم جيروب أوبنهايمر الذي قاد مشروع مانهاتن لتطوير القنبلة الذرية خلال الحرب العالمية الثانية. يُظهر الفيلم رحلته العلمية من جامعة كاليفورنيا إلى لوس ألاموس، والصراعات الأخلاقية التي واجهها بعد نجاح المشروع واختبار القنبلة النووية الأولى.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/7/8/4/3/2/8/784328-oppenheimer-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2023, quality: "1080p", rating: 8.3, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-374720", title: "خليل الجزء الثاني", originalTitle: "Dune: Part Two", slug: "dune-part-two-2024", overview: "يواصل بول أتريدس رحلته مع الفريمين في صحراء كوكب أراكيس بعد سقوط عائلته. يتحول بول إلى زعيم عسكري وسياسي قوي بين الفريمين ويسعى للانتقام من عائلة هاركونين. يواجه بول تحديات الحب والواجب والقدر بينما يحاول منع مستقبل مروع رآه في رؤيته.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/6/1/7/4/4/3/617443-dune-part-two-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2024, quality: "1080p", rating: 8.2, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-326279", title: "سبايدرمان: إلى عالم العنكبوت", originalTitle: "Spider-Man: Into the Spider-Verse", slug: "spider-man-into-spider-verse-2018", overview: "مايلز موراليز مراهق من بروكلين يحصل على قدرات العنكبوت بعد لدغة عنكبود مشع. يكتشف مايلز أنه ليس الوحيد الذي يحمل هذه القدرات عندما يلتقي بسبايدرمان من أبعاد مختلفة. يجب عليهم التعاون لمنع الملك البلور من تدمير كل الأبعاد.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/2/5/1/9/4/3/251943-spider-man-into-the-spider-verse-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2018, quality: "1080p", rating: 8.4, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-987905", title: "سبايدرمان: عبر عالم العنكبوت", originalTitle: "Spider-Man: Across the Spider-Verse", slug: "spider-man-across-spider-verse-2023", overview: "مايلز موراليز يعود في مغامرة جديدة عبر الأبعاد المتعددة. بعد أن التقى بشارة قوية من شخصية سبايدرمان الشريرة، يجد مايلز نفسه في صراع مع فريق سبايدرمان عبر الأبعاد. يجب عليه أن يجد طريقة للعودة إلى عالمه وحماية أحبائه.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/4/9/7/6/3/1/497631-spider-man-across-the-spider-verse-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2023, quality: "1080p", rating: 8.6, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-634649", title: "سبايدرمان: لا مفر من البيت", originalTitle: "Spider-Man: No Way Home", slug: "spider-man-no-way-home-2021", overview: "بعد أن كشف هوية سبايدرمان للعالم، يطلب بيتر باركر من ستيفن سترينج أن يلقي تعويذة لجعل الجميع ينسي هويته. لكن التعويذة تنحرف وتجلب أعداء سبايدرمان من عوالم أخرى. يجب على بيتر التعامل مع ثلاثة أشرار من أبعاد مختلفة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/6/0/7/8/7/560787-spider-man-no-way-home-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2021, quality: "1080p", rating: 8.2, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-299534", title: "المنتقمون: نهاية اللعبة", originalTitle: "Avengers: Endgame", slug: "avengers-endgame-2019", overview: "بعد هزيمةThanos ومحو نصف الكائنات الحية في الكون، يواجه المنتقمون المتبقون واقعاً مأساوياً. يكتشفون إمكانية السفر عبر الزمن باستخدام الجسيمات الكمية ويتحدون من أجل استعادة الأحجار اللانهائية وإعادة كل من تم محوه.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/2/2/6/6/6/0/226660-avengers-endgame-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2019, quality: "1080p", rating: 8.3, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-299536", title: "المنتقمون: حرب لا نهائية", originalTitle: "Avengers: Infinity War", slug: "avengers-infinity-war-2018", overview: "ثانوس يصل إلى الأرض بحثاً عن أحجار اللانهارية الأخيرة. يتحد أبطال مارفل من مختلف أنحاء الكون لمواجهة هذا التهديد الوجودي. في معركة ملحمية، يفشل المنتظمون في إيقاف ثانوس الذي ينجح في محو نصف الحياة في الكون بنقرة إصبعه.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/2/2/6/6/6/1/226661-avengers-infinity-war-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2018, quality: "1080p", rating: 8.4, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-340398", title: "لالا لاند", originalTitle: "La La Land", slug: "la-la-land-2016", overview: "ميا طموحة تمثيل تنتقل إلى لوس أنجلوس وتعمل ككافييرة بينما تحضر جلسات تجارب أدوار. ساباستيان موسيقي جاز يحلم بفتح نادٍ خاص به. يلتقيان ويقعان في الحب، لكن طموحاتهما المهنية تبدأ بإبعادهما عن بعضهما البعض.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/2/4/0/3/4/4/240344-la-la-land-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2016, quality: "1080p", rating: 8.0, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-353081", title: "الماتريكس", originalTitle: "The Matrix", slug: "matrix-1999", overview: "توماس أندرسون هو مبرمج كمبيوتر يعيش حياة مزدوجة. في النهار يعمل في شركة برمجيات، وفي الليل يصبح هاكر يعرف باسم نيو. يكتشف نيو أن العالم الذي يعيش فيه ليس حقيقياً بل هو محاكاة حاسوبية تتحكم بها آلات ذكية. عليه أن يختار بين الوهم والواقع.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/5/1/8/51518-the-matrix-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1999, quality: "1080p", rating: 8.7, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-7451", title: "الرحلة المذهلة", originalTitle: "千と千尋の神隠し", slug: "spirited-away-2001", overview: "تنتقل الفتاة تشيهيرو مع عائلتها إلى منزل جديد. أثناء الطريق، تدخل عائلتها نفقاً غريباً يؤدي بهم إلى عالم سحري من الأرواح. يجب على تشيهيرو العمل في حمام الأرواح لإيجاد طريقة لإنقاذ والديها الذين تحولا إلى خنازير والعودة إلى العالم البشري.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/9/2/1/51921-spirited-away-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2001, quality: "1080p", rating: 8.6, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-449924", title: "سكاكين خارجية", originalTitle: "Knives Out", slug: "knives-out-2019", overview: "يُعثر على الكاتب الشهير هارلان ثومبري ميتاً بعد عيد ميلاده الخامس والثمانين. يستدعي المحقق الخاص دانيال كريسي للتحقيق في القضية. يكتشف كريسي أن كل فرد في هذه العائلة المكونة من شخصيات غريبة لديه دافع لقتل ثومبري.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/4/7/5/3/7/0/475370-knives-out-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2019, quality: "1080p", rating: 7.9, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-438631", title: "خليل", originalTitle: "Dune", slug: "dune-2021", overview: "في المستقبل البعيد، ينتقل بول أتريدس مع عائلته إلى كوكب أراكيس الصحراوي الذي يُعرف بخليل الكون. هذا الكوكب هو المصدر الوحيد لمادة التوابل الأكثر قيمة في الكون. تتكشف مؤامرات خطيرة تهدد حياة عائلة أتريدس بأكملها.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/2/5/1/6/52516-django-unchained-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2021, quality: "1080p", rating: 8.0, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-447365", title: "نادي الشعراء الأموات", originalTitle: "Dead Poets Society", slug: "dead-poets-society-1989", overview: "جون كيتينغ معلم شعر غير تقليدي يبدأ التدريس في أكاديمية ويلتون الصارمة. يلهم تلاميذه بأن يعيشوا حياتهم بكل إيجابية وشغف، وأن يتبعوا شغفهم ويمارسوا فن الشعر. تؤثر أفكاره بشكل عميق في حياة تلاميذه.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/8/4/6/51846-dead-poets-society-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1989, quality: "1080p", rating: 8.1, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-102899", title: "ذئب وول ستريت", originalTitle: "The Wolf of Wall Street", slug: "wolf-wall-street-2013", overview: "جوردان بيلفورت يتدرب كوسيط مالي في وول ستريت. بعد انهيار الشركة، ينتقل إلى شركة صغيرة ويبدأ ببناء إمبراطورية مالية من خلال عمليات احتيال واسعة. يعيش حياة من البذخ والإدمان بينما تستمر عمليات الاحتيال حتى يتدخل مكتب التحقيقات الفيدرالي.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/8/6/1/1/4/86114-the-wolf-of-wall-street-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2013, quality: "1080p", rating: 8.2, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-603", title: "الماتريكس: إعادة التحميل", originalTitle: "The Matrix Reloaded", slug: "matrix-reloaded-2003", overview: "يواصل نيو رحلته في تحرير البشرية من سيطرة الآلات. يكتشف أن المدينة الأخيرة للبشرzion معرضة لخطر هجوم الآلات. مع زملائه في المقاومة، يتوجه نيو للاستشارة من العرافة ويحاول إيجاد طريقة لإنقاذ المدينة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/5/1/8/51518-the-matrix-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2003, quality: "1080p", rating: 7.0, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-804735", title: "باتمان", originalTitle: "The Batman", slug: "batman-2022", overview: "باتمان في سنواته الأولى من محاربة الجريمة في مدينة غوثام. يواجه لغز الغامض الذي يترك خلفه أدلة غامضة. يجب على باتمان كشف هوية هذا القاتل المتسلسل قبل أن يوقع المزيد من الضحايا، ويتعاون مع المفتشة كاتي كيڤ ومدعي العام الجديد.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/3/4/8/9/1/4/348914-the-batman-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2022, quality: "1080p", rating: 7.7, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-338762", title: "فندق جراند بودابست", originalTitle: "The Grand Budapest Hotel", slug: "grand-budapest-hotel-2014", overview: "غوستاف إتش مدير الفندق الأيقوني في جبال ألب خلال الثلاثينيات. يقيم علاقة مع إحدى نزلائه المسنات اللواتي يورثنه لوحة ثمينة. بعد وفاتها، يتهم غوستاف بالقتل ويصبح هارباً من العدالة مع صبيه المخلص زيرو.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/9/5/1/1/3/95113-the-grand-budapest-hotel-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2014, quality: "1080p", rating: 8.1, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-324786", title: "سوط العذاب", originalTitle: "Whiplash", slug: "whiplash-2014", overview: "أندرو نيمان طالب طبول في معهد الموسيقى المرموق. يكتشفه المايسترو تيرينس فليتشر المعروف بقسوته ويدفعه إلى حدود القوة الجسدية والنفسية. يتحول طموح أندرو إلى هوس يهدد صحته وعلاقاته بأحبائه.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/8/4/6/51846-dead-poets-society-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2014, quality: "1080p", rating: 8.5, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-502356", title: "فيلم سوبر ماريو", originalTitle: "The Super Mario Bros. Movie", slug: "super-mario-movie-2023", overview: "ماريو وإخوته لويجي يعملان كسباكين في بروكلين. بالصدفة يسقطان في أنبوب سحري يوصلهما إلى عالم الفطر السحري. يُختطف لويجي على يد الديناوور بينما يتحالف ماريو مع الأميرة بيتش لمحاربة باوزر وإنقاذ أخيه والعالم.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/9/5/7/0/5/0/957050-superman-2025-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2023, quality: "1080p", rating: 7.1, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-1022789", title: "الخطاة", originalTitle: "Sinners", slug: "sinners-2025", overview: "توأمان يعودان إلى مسقط رأسهما في ولاية ميسيسيبي ثلاثينيات القرن الماضي بعد سنوات من الغياب. يحاولان فتح نادٍ ليلٍ في منزلهم القديم لكن يواجهان تهديداً خارقاً للطبيعة من مصاصي دماء يسكنون المنطقة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/1/1/1/6/6/0/0/1116600-sinners-2025-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2025, quality: "1080p", rating: 7.8, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-748783", title: "القائمة", originalTitle: "The Menu", slug: "menu-2022", overview: "مجموعة من الأثرياء يسافرون إلى جزيرة نائية لتجربة وجبة فاخرة في مطعم حصري يقوده الشيف سلوفيك. كل طبق يحمل مفاجأة صادمة. يكشف الشيف تدريجياً عن نيته المظلمة في تحويل هذه الوجبة إلى تجربة رهيبة لن ينساها أحد.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/6/2/1/51621-good-will-hunting-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2022, quality: "1080p", rating: 7.2, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-58221", title: "الشيطان يرتدي برادا", originalTitle: "The Devil Wears Prada", slug: "devil-wears-prada-2006", overview: "آندي ساكس خريجة جامعية تحلم بالصحافة الاستقصائية. توظفها ميراندا بريستلي المحررة الشهيرة في مجلة الأزياء الراقية Runway. على الرغم من افتقارها للخبرة في الأزياء، تتحول آندي تدريجياً لامرأة أنيقة وفعالة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/7/1/2/51712-the-devil-wears-prada-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2006, quality: "1080p", rating: 6.9, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-76241", title: "سائق الأطفال", originalTitle: "Baby Driver", slug: "baby-driver-2017", overview: "بيبي سائق شاحنة هروب بارع يعمل لعصابة إجرامية بقيادة دوق. يعاني من طنين في أذنه مما يجبره على الاستماع للموسيقى باستمرار. يلتقي بديبورا ويقع في حبها ويقرر الخروج من عالم الجريمة بعد عملية أخيرة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/2/6/8/9/5/0/268950-baby-driver-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2017, quality: "1080p", rating: 7.6, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-512195", title: "اخرج", originalTitle: "Get Out", slug: "get-out-2017", overview: "كريس واشنطن شاب أسود يسافر مع صديقته البيضاء روز لزيارة عائلتها في الريف. يشعر كريس بعدم الارتياح تجاه سلوك العائلة والعمال الأسود الغريبين في المنطقة. يكتشف تدريجياً حقيقة مرعبة حول نوايا عائلة روز الحقيقية.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/3/5/3/1/1/7/353117-get-out-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2017, quality: "1080p", rating: 7.7, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-122917", title: "الإشراقة", originalTitle: "The Shining", slug: "shining-1980", overview: "جاك تورانس كاتب يأخذ وظيفة حارس في فندق أوفرلوك المغلق خلال الشتاء. ينتقل مع زوجته ويندي وابنهما داني الذي يمتلك قدرات خارقة. القوى الشريرة في الفندق تبدأ بالتسلل إلى عقل جاك وتدفعه تدريجياً نحو الجنون.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/3/4/5/51345-se7en-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1980, quality: "1080p", rating: 8.4, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-698507", title: "المادة", originalTitle: "The Substance", slug: "substance-2024", overview: "إيليزا إسبيك سيدة أعمال في الخمسينيات تُقيل من عملها كمقدمة برنامج تلفزيوني بسبب تقدمها في العمر. تكتشف عقاراً سرياً يُدعى المادة يمكنه خلق نسخة شابة ومثالية منها. لكن استخدام العقار يأتي بنتائج مأساوية.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/8/3/8/1/4/0/838140-the-substance-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2024, quality: "1080p", rating: 7.0, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-429617", title: "منتصف الصيف", originalTitle: "Midsommar", slug: "midsommar-2019", overview: "داني تعاني من صدمة نفسية بعد فقدان عائلتها. تسافر مع صديقها كريستيان وأصدقائه إلى قرية نائية في السويد لحضور مهرجان منتصف الصيف التقليدي. الاحتفالات السعيدة تتحول تدريجياً إلى طقوس مرعبة وغريبة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/4/5/9/5/6/4/459564-midsommar-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2019, quality: "1080p", rating: 7.1, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-274", title: "صمت الحملان", originalTitle: "The Silence of the Lambs", slug: "silence-lambs-1991", overview: "كلاريس ستارلنج عميلة مبتدئة في مكتب التحقيقات الفيدرالي تُكلف بالتحقيق في قضية قاتل متسلسل يُدعى بوفالو بيل. تطلب المساعدة من الطبيب النفسي والقاتل المدان هانيبال ليكتر الذي يوافق على مساعدتها مقابل معلومات شخصية عنها.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/3/4/5/51345-se7en-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1991, quality: "1080p", rating: 8.6, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-533514", title: "كان هناك مرة في هوليوود", originalTitle: "Once Upon a Time in Hollywood", slug: "once-upon-hollywood-2019", overview: "ريك دالتون ممثل سابق يعيش أيامه الأخيرة في هوليوود عام 1969. يعيش مع بدلائه الشخصي كليف بوث. يدور الفيلم في خلفية التغيرات الثقافية في هوليوود وتتقاطع قصتهما مع قصة الممثلة شارون تيت الجارة.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/3/9/7/8/5/9/397859-once-upon-a-time-in-hollywood-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2019, quality: "1080p", rating: 7.6, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-12555", title: "موهبة الصيد الجيدة", originalTitle: "Good Will Hunting", slug: "good-will-hunting-1997", overview: "ويل هانتينغ شاب عبقري يعمل كنادل في جامعة MIT. يكتشف أستاذ الرياضيات موهبته الاستثنائية في حل المسائل الرياضية المعقدة. يُحال ويل للعلاج النفسي مع الطبيب شون ماكواير الذي يساعده على مواجهة مخاوفه.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/6/2/1/51621-good-will-hunting-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1997, quality: "1080p", rating: 8.3, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-11860", title: "مزايا أن تكون خجولاً", originalTitle: "The Perks of Being a Wallflower", slug: "perks-wallflower-2012", overview: "تشارلي طالب في المرحلة الثانوية يعاني من القلق والاكتئاب. يصادق سام وباتريك وهما أخ وأخت بالتبني في السنة الأخيرة. يتعلم تشارلي دروساً مهمة عن الصداقة والحب والموسيقى ويبدأ في التغلب على صدماته الماضية.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/7/1/3/3/8/71338-the-perks-of-being-a-wallflower-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2012, quality: "1080p", rating: 7.7, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-12477", title: "الأسبعة المميتة", originalTitle: "Se7en", slug: "se7en-1995", overview: "المفتشان سومرست وميلز يحققان في سلسلة من جرائم القتل المرعبة التي تمثل الخطايا السبع المميتة. كل جريمة أكثر بشاعة من سابقتها. يقود التحقيق المفتشان إلى قاتل محنك يخطط لجريمته الأخيرة الكبرى.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/5/1/3/4/5/51345-se7en-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 1995, quality: "1080p", rating: 8.6, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-456740", title: "ويكيد", originalTitle: "Wicked", slug: "wicked-2024", overview: "إلفابا فتاة خضراء البشرة تُعتبر شريرة في أرض أوز. تبدأ قصتها عندما تلتقي بغلندا الشقراء الجميلة في المدرسة. تطور علاقة صداقة معقدة بينهما بينما تتكشف حقيقة الطبيعة الشريرة لحاكم أوز.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/3/3/7/0/3/6/337036-wicked-2024-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2024, quality: "1080p", rating: 7.4, mediaType: "movie", site: "tmdb", isPublished: true },
  { id: "tmdb-1024550", title: "أنورا", originalTitle: "Anora", slug: "anora-2024", overview: "أنورا فتاة تعمل في نادٍ ليلي في بروكلين تلتقي بإيفان ابن رجل أعمال روسي ثري. يتزوجان بشكل مفاجئ ويبدآن حياة جديدة معاً. لكن عائلة إيفان ترفض هذا الزواج وتسعى لإبطاله مما يضع أنورا في موقف صعب.", posterUrl: "https://a.ltrbxd.com/resized/film-poster/9/5/9/5/4/0/959540-anora-0-500-0-750-crop.jpg", backdropUrl: "", releaseYear: 2024, quality: "1080p", rating: 7.6, mediaType: "movie", site: "tmdb", isPublished: true },
];

async function main() {
  console.log("🎬 بدء زراعة بيانات الأفلام من TMDB...");
  console.log(`📦 عدد الأفلام: ${movies.length}`);

  // Delete existing tmdb movies to avoid duplicates
  const deleteResult = await prisma.movie.deleteMany({
    where: { site: "tmdb" },
  });
  console.log(`🗑️ تم حذف ${deleteResult.count} فيلم قديم`);

  // Seed all movies
  let created = 0;
  for (const movie of movies) {
    // Extract numeric tmdbId from the id string (e.g., "tmdb-157336" → 157336)
    const tmdbIdStr = movie.id.replace("tmdb-", "");
    const tmdbIdNum = parseInt(tmdbIdStr, 10);

    await prisma.movie.create({
      data: {
        id: movie.id,
        title: movie.title,
        originalTitle: movie.originalTitle,
        slug: movie.slug,
        overview: movie.overview,
        posterUrl: movie.posterUrl,
        backdropUrl: movie.backdropUrl || null,
        releaseYear: movie.releaseYear,
        quality: movie.quality,
        rating: movie.rating,
        mediaType: movie.mediaType,
        site: movie.site,
        siteUrl: `https://www.themoviedb.org/movie/${tmdbIdNum}`,
        isPublished: movie.isPublished,
      },
    });
    created++;
  }

  console.log(`✅ تم إنشاء ${created} فيلم بنجاح!`);

  // Verify
  const totalMovies = await prisma.movie.count({
    where: { site: "tmdb", isPublished: true },
  });
  console.log(`📊 إجمالي الأفلام المنشورة: ${totalMovies}`);

  // Show sample
  const sample = await prisma.movie.findMany({
    where: { site: "tmdb" },
    take: 5,
    orderBy: { rating: "desc" },
  });
  console.log("\n🔝 أعلى 5 أفلام تقييماً:");
  for (const m of sample) {
    console.log(`   ⭐ ${m.rating.toFixed(1)} - ${m.title} (${m.releaseYear})`);
  }
}

main()
  .catch((e) => {
    console.error("❌ فشلت عملية الزراعة:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
